### ISSUE TITLE
通义千问的Qwen-max

### ISSUE THREAD

**Issue by li5bo5** [GeekinGH/AiChatHelper#2]

**Comment by li5bo5** [comment]
![微信截图_20240130111650](https://github.com/GeekinGH/AiChatHelper/assets/6594141/38f6f1bc-ccd7-49b7-9134-ca094a1c6820)

**Comment by GeekinGH** [comment]
已经增加qwen-max

**Comment by li5bo5** [comment]
> 已经增加qwen-max

大佬牛逼~~~~
