### ISSUE TITLE
大佬可以支持Bard吗？

### ISSUE THREAD

**Issue by li5bo5** [GeekinGH/AiChatHelper#4]
大佬可以支持Bard吗？

**Comment by GeekinGH** [comment]
Bard有公布API吗？可以免费使用的吗？

**Comment by li5bo5** [comment]
> Bard有公布API吗？可以免费使用的吗？

好像有办法获取api吧？免费的啊、有谷歌账号就能用，chatgpt还要手机号绑定才给spi，bard打开网页、同意协议直接就用了

**Comment by li5bo5** [comment]
> Bard有公布API吗？可以免费使用的吗？

和gemini一样挂梯子直接访问，我昨晚试了，挺好用的，出图贼快

**Comment by GeekinGH** [comment]
网页版免费用不等于有API可以用。你是否有它的API的文档地址？还有微信助手只支持文本传输，你要的绘图功能也实现不了。

**Comment by li5bo5** [comment]
> 网页版免费用不等于有API可以用。你是否有它的API的文档地址？还有微信助手只支持文本传输，你要的绘图功能也实现不了。

我看了一下，准确的讲，Bard没有开放api，但是可以通过
`__Secure-1PSID`来实现调用
参考文档地址：
https://blog.csdn.net/favxxx/article/details/133033642
https://github.com/Alfex4936/Bard-rs
https://www.bilibili.com/video/BV1Nk4y1j7j9/
https://chatgpt.yundongfang.com/222299/.html
https://zhuanlan.zhihu.com/p/631178245?utm_id=0

**Comment by GeekinGH** [comment]
这种接入方式暂时不考虑了。另外Bard已经被合并为Gemini。
