### ISSUE TITLE
netlify注册不成功，求服务器部署办法

### ISSUE THREAD

**Issue by penhuowa** [GeekinGH/AiChatHelper#6]
自己有服务器的怎么搭，大佬

**Comment by GeekinGH** [comment]
在自己的服务器搭建的话需要修改代码，等我有空再写。

**Comment by GeekinGH** [comment]
已经写好了可以在自己服务器搭建的代码，请到这个仓库：https://github.com/GeekinGH/AiChatHelperNodejs/
